name: "This is Staging Workflow"

run-name: "This is run by ${{ github.actor }}, on ${{ github.event_name }} event"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  First-Job:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out the repository"
        uses: actions/checkout@v4
      - name: "Connecting to AWS"
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'ubuntu@51.20.5.52'
          privatekey: ${{ secrets.EC2_SERVER }}
          command: |
            export NVM_DIR=/home/ubuntu/.nvm
            source /home/ubuntu/.nvm/nvm.sh
            cd /home/ubuntu/Devops-Assignment2/App
            git pull origin main
            cd App/
            killall node
            forever start index.js
      - name: "Notify on success"
        if: success()
        run: echo " The Staging Completed"
      - name: "Notify on Failure"
        if: failure()
        run: echo "The Stating Failed"
